### ISSUE TITLE
Missing configuration option when installing Ironic inspector: 'baremetal_server_inspector_enabled'

### ISSUE THREAD

**Issue by gbraad** [jriguera/ansible-ironic-standalone#4]
Currently when installing the Ironic Inspector, the installation for all-in-one will fail as `baremetal_server_inspector_enabled` is undefined.

Traceback:

```
fatal: [ironic]: FAILED! => {
    "failed": true,
    "msg": "The conditional check 'ironic_conductor and ironic_inspector_enabled' failed. The error was: error while evaluating conditional (ironic_conductor and ironic_inspector_enabled): 'baremetal_server_inspector_enabled' is undefined

    The error appears to have been in '/home/gerard/ansible-ironic-standalone/roles/ironic/tasks/main.yml': line 37, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:


    - include: setup_inspector.yml
    ^ here
    "
}
```

**Comment by jriguera** [comment]
Ok, this one is because in the inventory file  'hosts/allinone' the variable `baremetal_server_inspector_enabled` has to be defined. I will update such inventory file.

**Comment by jriguera** [comment]
Could you try again with the new inventory file on master.

https://github.com/jriguera/ansible-ironic-standalone/commit/e0c77f1a31169ebe122bc7cad6c069781894d6d6

**Comment by jriguera** [comment]
Fixed with https://github.com/jriguera/ansible-ironic-standalone/commit/e0c77f1a31169ebe122bc7cad6c069781894d6d6
