### ISSUE TITLE
Missing configuration option when installing Ironic inspector: 'baremetal_server_ironic_api'

### ISSUE THREAD

**Issue by gbraad** [jriguera/ansible-ironic-standalone#5]
When deploying as all-in-one, the deployment will fail because of a missing configuration option:

```
TASK [ironic : Generate the main configuration file] ***************************
fatal: [ironic]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'baremetal_server_ironic_api' is undefined"}
```

**Comment by jriguera** [comment]
It is a similar issue as https://github.com/jriguera/ansible-ironic-standalone/issues/4

**Comment by jriguera** [comment]
Could you try again with the new inventory file on master.

https://github.com/jriguera/ansible-ironic-standalone/commit/e0c77f1a31169ebe122bc7cad6c069781894d6d6

**Comment by jriguera** [comment]
Fixed with https://github.com/jriguera/ansible-ironic-standalone/commit/e0c77f1a31169ebe122bc7cad6c069781894d6d6
