### ISSUE TITLE
Generation of main Ironic configuration file fails

### ISSUE THREAD

**Issue by gbraad** [jriguera/ansible-ironic-standalone#6]
```
TASK [ironic : Generate the main configuration file] ***************************
task path: /home/gerard/ansible-ironic-standalone/roles/ironic/tasks/configure.yml:23
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "dest": "/etc/ironic/ironic.conf",
            "group": "ironic",
            "mode": 420,
            "owner": "ironic",
            "src": "ironic.conf.j2"
        },
        "module_name": "template"
    },
    "msg": "error: nothing to repeat"
}
fatal: [ironic]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "dest": "/etc/ironic/ironic.conf",
            "group": "ironic",
            "mode": 420,
            "owner": "ironic",
            "src": "ironic.conf.j2"
        },
        "module_name": "template"
    },
    "msg": "error: nothing to repeat"
}
```

**Comment by gbraad** [comment]
This should be *WONTFIX*

This is not a problem on Ansible 2.1.0.0, but because of https://github.com/jriguera/ansible-ironic-standalone/issues/3 it is not possible to run the whole playbook `setup_ironic.qml` or `site.yml` to completion on Ansible 2.1.0.0

**Comment by gbraad** [comment]
This problem is not Ansible version specific

**Comment by jriguera** [comment]
Could you re-run the playbooks with -vvvv?  Are you running Centos 7.2?

**Comment by gbraad** [comment]
This was the only output (it was run with `-vvvv`). It is likely something related to the templating and a expression (such as a regexp) that fails. But haven't been able to pinpoint it yet.

https://gist.github.com/gbraad/86a735e3907d2af983f95041660c75fc

**Comment by ScarabMonkey** [comment]
I have this same problem on CentOS 7.2 - do you have a workaround?

```
TASK [ironic : Generate the main configuration file] ***************************
task path: /opt/ironic/ansible-ironic-standalone/roles/ironic/tasks/configure.yml:23
fatal: [ironic]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"dest": "/etc/ironic/ironic.conf", "group": "ironic", "mode": 420, "owner": "ironic", "src": "ironic.conf.j2"}, "module_name": "template"}, "msg": "error: nothing to repeat"}
```

I have tried deleting the existing ironic.conf and also tried disabling SELinux - but the result was exactly the same.

**Comment by jriguera** [comment]
I am not able to reproduce this issue. I have tested with ansible 2.1 and a vagrant VM with centos-7.2 (see Vagrantfile). Could you tell me which ansible version are you using?

Anyway, after googling a bit, and assuming you are using the inventory provided, I am suspecting about regex expressions in the template rendering. In your target server, could you check which version of jinja are you running (`sudo pip list | grep -i jinja`)?

**Comment by ScarabMonkey** [comment]
I am using a minimal install of CentOS 7 so I don't currently have pip installed... however, yum tells me this:
`python-jinja2.noarch                                          2.7.2-2.el7                                          @base`

**Comment by jriguera** [comment]
Ok, just for testing, (assuming you are using mysql)  could you please change the following section in the ironic.conf template: https://github.com/jriguera/ansible-ironic-standalone/blob/master/roles/ironic/templates/ironic.conf.j2#L544 :

```
{% if ironic_database_connection is defined and ironic_database_connection | match("mysql://.*") -%}
connection="{{ ironic_database_connection }}"
{% else %}
{% if not ironic_database_connection is defined -%}
{% set ironic_database_connection="sqlite:///var/lib/ironic/ironic.db" %}
{% endif %}
connection="{{ ironic_database_connection }}"

# The file name to use with SQLite. (string value)
sqlite_db={{ ironic_database_connection | basename }}

# If True, SQLite uses synchronous mode. (boolean value)
sqlite_synchronous=true
{% endif %}
```

to just:

```
connection="{{ ironic_database_connection }}"
```

and run again, please

**Comment by piward** [comment]
Hi there, also having the same issue on a RHEL 7.2 server - we tested with Vagrant/CentOS 7.2 a couple weeks ago and didn't run into this issue. 

Even with the suggested change to ironic.conf.j2 we get the same error:

> TASK [ironic : Generate the main configuration file] ***************************
> task path: /home/ironic/ansible-ironic-standalone/roles/ironic/tasks/configure.yml:23
> fatal: [ironic]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"dest": "/etc/ironic/ironic.conf", "group": "ironic", "mode": 420, "owner": "ironic", "src": "ironic.conf.j2"}, "module_name": "template"}, "msg": "error: nothing to repeat"}

**Comment by ScarabMonkey** [comment]
Unfortunately that didn't make any difference - still the same error.
(I edited roles/ironic/templates/ironic.conf.j2 from line 544)

**Comment by jriguera** [comment]
Are you running this python version?:

```
$ python
Python 2.7.5 (default, Nov 20 2015, 02:00:19) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by piward** [comment]
Looks like the RHEL version of python was compiled with a slightly older version of GCC. CentOS 7.2 has the version you posted though. 

```
$ python
Python 2.7.5 (default, Oct 11 2015, 17:47:16)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by ScarabMonkey** [comment]
On CentOS 7.2 I do indeed have that Python:

```
[ansible-ironic-standalone]$ python
Python 2.7.5 (default, Nov 20 2015, 02:00:19) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```

This is a fresh install of CentOS on an ESXi VM.

**Comment by ScarabMonkey** [comment]
I found a 'regex_replace' and a 'search' in the template too - tried removing those as well, but still no joy. I'm not sure where the regex is coming from...

**Comment by ScarabMonkey** [comment]
I managed to get past this stage by removing regex references in a couple of places as shown by this git diff output: 

```
diff --git a/roles/ironic/tasks/configure.yml b/roles/ironic/tasks/configure.yml
index d06c532..9ec0c87 100644
--- a/roles/ironic/tasks/configure.yml
+++ b/roles/ironic/tasks/configure.yml
@@ -52,7 +52,7 @@
     when: not _ironic_previous

   when: >
-    not ironic_database_connection | search("sqlite://.*")
+    not ironic_database_connection
     and _ironic_api_reinstalled
     and _ironic_updated

diff --git a/roles/ironic/templates/ironic.conf.j2 b/roles/ironic/templates/ironic.conf.j2
index 3a800c0..ae8270e 100644
--- a/roles/ironic/templates/ironic.conf.j2
+++ b/roles/ironic/templates/ironic.conf.j2
@@ -541,20 +541,7 @@ backend=sqlalchemy
 # Deprecated group/name - [DEFAULT]/sql_connection
 # Deprecated group/name - [DATABASE]/sql_connection
 # Deprecated group/name - [sql]/connection
-{% if ironic_database_connection is defined and ironic_database_connection | match("mysql://.*") -%}
 connection="{{ ironic_database_connection }}"
-{% else %}
-{% if not ironic_database_connection is defined -%}
-{% set ironic_database_connection="sqlite:///var/lib/ironic/ironic.db" %}
-{% endif %}
-connection="{{ ironic_database_connection }}"
-
-# The file name to use with SQLite. (string value)
-sqlite_db={{ ironic_database_connection | basename }}
-
-# If True, SQLite uses synchronous mode. (boolean value)
-sqlite_synchronous=true
-{% endif %}

 # The SQLAlchemy connection string to use to connect to the
 # slave database. (string value)
@@ -1252,7 +1239,7 @@ enabled=true
 # ironic-discoverd HTTP endpoint. If this is not set, the
 # ironic-discoverd client default (http://127.0.0.1:5050) will
 # be used. (string value)
-service_url={{ ironic_inspector_service_url | regex_replace('^(https?://)([^:^/]*)(:\\d*)?(.*)?$', '\\1\\2\\3') }}
+service_url={{ ironic_inspector_service_url }}

 # period (in seconds) to check status of nodes on inspection
 # (integer value)
```

merely commenting out those bits didn't seem to help?

**Comment by piward** [comment]
We were doing the same thing to try and find the offending regex. The line is this: 

`service_url={{ ironic_inspector_service_url | regex_replace('^(https?://)([^:^/]*)(:\\d*)?(.*)?$', '\\1\\2\\3') }}`

I made a simple playbook to test this, and it works fine on Mac but fails on CentOS 7.2/RHEL 7.2: 

```
- hosts: 127.0.0.1
  connection: local
  vars:
    - test1: "{{ 'http://10.1.1.10:5050/v1/' | regex_replace('^(https?://)([^:^/]*)(:\\d*)?(.*)?$', '\\1\\2\\3') }}"
  tasks:
    - debug: var={{ item }}
      with_items: [ test1 ]
```

The error on EL: 

```
[vagrant@localhost ~]$ ansible-playbook playbook.yml
PLAY [127.0.0.1] ***************************************************************

TASK [setup] *******************************************************************
ok: [127.0.0.1]

TASK [debug] *******************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: error: {{ 'http://10.1.1.10:5050/v1/' | regex_replace('^(https?://)([^:^/]*)(:\d*)?(.*)?$', '\1\2\3') }}: nothing to repeat
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @playbook.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by piward** [comment]
The actual error is caused by the last group match which takes the path (/v1/, /v2/ etc.): 
`(.*)?$`

If you remove the '?' to make it not optional, it works without error. I'm not sure if there is a reason behind this, but even if that text doesn't exist in the url the regex without the '?' still works fine for us.  I have no idea if there is a reason behind the '?' and if this could cause issues elsewhere, but we can at least generate the ironic.conf this way. 

The "working" regex: 
`
service_url={{ ironic_inspector_service_url | regex_replace('^(https?://)([^:^/]*)(:\\d*)?(.*)$', '\\1\\2\\3') }}
`

Hope this helps!

**Comment by ScarabMonkey** [comment]
Thanks @piward that does appear to be the offending regex - I have now got further in the playbook... although hit another hurdle! It is taking almost 20 minutes per run to get to this point ... do you know any shortcuts!?

**Comment by ScarabMonkey** [comment]
Okay, got past my other hurdles - SELinux and Proxy problems. Now the playbook finishes!

**Comment by jriguera** [comment]
Thanks guys, these days I am traveling and I cannot test things, I will
investigate this at the weekend.

**Comment by jriguera** [comment]
I have updated the role with the fix provided by @piward (sorry I made a mistake referring to you in the commit message). Thanks for helping to debug this issue.

**Comment by gbraad** [comment]
Ran an install just now and it finishes... thanks!
